# Generated by Django 4.2.17 on 2024-12-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('domain_name', models.CharField(max_length=30)),
                ('protocol', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=30)),
                ('image', models.JSONField()),
                ('stylesheets', models.IntegerField()),
            ],
        ),
    ]
