# Generated by Django 4.2.17 on 2024-12-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitcoinInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitcoin_eur', models.DecimalField(decimal_places=5, max_digits=8)),
                ('eur_to_gbp', models.DecimalField(decimal_places=5, max_digits=8)),
                ('bitcoin_gbp', models.DecimalField(decimal_places=5, max_digits=8)),
            ],
        ),
    ]
