# Generated by Django 4.2.17 on 2024-12-19 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BitcoinInfo',
        ),
    ]
